//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nipema.Tyonohjaus.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nipema.Tyonohjaus.Client.Localization.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Edit Products.
        /// </summary>
        public static string AddOrEdit {
            get {
                return ResourceManager.GetString("AddOrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product property.
        /// </summary>
        public static string AddProductProperty {
            get {
                return ResourceManager.GetString("AddProductProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to workflow.
        /// </summary>
        public static string AddToWorkflow {
            get {
                return ResourceManager.GetString("AddToWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trolley.
        /// </summary>
        public static string AddTrolley {
            get {
                return ResourceManager.GetString("AddTrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to workflow.
        /// </summary>
        public static string ButtonAddToWorkflow {
            get {
                return ResourceManager.GetString("ButtonAddToWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string ButtonEditProduct {
            get {
                return ResourceManager.GetString("ButtonEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string ButtonRemoveProduct {
            get {
                return ResourceManager.GetString("ButtonRemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel load.
        /// </summary>
        public static string CancelLoading {
            get {
                return ResourceManager.GetString("CancelLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        public static string CartEstimatedArrival {
            get {
                return ResourceManager.GetString("CartEstimatedArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose product.
        /// </summary>
        public static string ChooseProduct {
            get {
                return ResourceManager.GetString("ChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose monitor.
        /// </summary>
        public static string ChooseScreen {
            get {
                return ResourceManager.GetString("ChooseScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string Clockwise {
            get {
                return ResourceManager.GetString("Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel loading?.
        /// </summary>
        public static string ConfirmCancelLoading {
            get {
                return ResourceManager.GetString("ConfirmCancelLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all history information?.
        /// </summary>
        public static string ConfirmHistoryDelete {
            get {
                return ResourceManager.GetString("ConfirmHistoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this product?.
        /// </summary>
        public static string ConfirmProductRemoval {
            get {
                return ResourceManager.GetString("ConfirmProductRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all these products?.
        /// </summary>
        public static string ConfirmProductsRemoval {
            get {
                return ResourceManager.GetString("ConfirmProductsRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter clockwise.
        /// </summary>
        public static string CounterClockwise {
            get {
                return ResourceManager.GetString("CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default oven time (min).
        /// </summary>
        public static string DefaultOvenTime {
            get {
                return ResourceManager.GetString("DefaultOvenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default pressure (bar).
        /// </summary>
        public static string DefaultPressure {
            get {
                return ResourceManager.GetString("DefaultPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete history.
        /// </summary>
        public static string DeleteHistory {
            get {
                return ResourceManager.GetString("DeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all products on the History-tab. Use this only when you are sure you want to delete all history information, for example when the computer is running low on space..
        /// </summary>
        public static string DeleteHistoryInfo {
            get {
                return ResourceManager.GetString("DeleteHistoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading point direction.
        /// </summary>
        public static string Direction1 {
            get {
                return ResourceManager.GetString("Direction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting point direction.
        /// </summary>
        public static string Direction2 {
            get {
                return ResourceManager.GetString("Direction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing point direction.
        /// </summary>
        public static string Direction3 {
            get {
                return ResourceManager.GetString("Direction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product instructions.
        /// </summary>
        public static string EditInstructions {
            get {
                return ResourceManager.GetString("EditInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export.
        /// </summary>
        public static string ExcelExport {
            get {
                return ResourceManager.GetString("ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Import.
        /// </summary>
        public static string ExcelImport {
            get {
                return ResourceManager.GetString("ExcelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Instructions.
        /// </summary>
        public static string ExistingInstructions {
            get {
                return ResourceManager.GetString("ExistingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is used by another program, please close the file and try again..
        /// </summary>
        public static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First row includes header.
        /// </summary>
        public static string FirstRow {
            get {
                return ResourceManager.GetString("FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History deleted.
        /// </summary>
        public static string HistoryDeleted {
            get {
                return ResourceManager.GetString("HistoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to database.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction locations.
        /// </summary>
        public static string InstructionPoints {
            get {
                return ResourceManager.GetString("InstructionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading instruction.
        /// </summary>
        public static string InstructionType1 {
            get {
                return ResourceManager.GetString("InstructionType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting instruction.
        /// </summary>
        public static string InstructionType2 {
            get {
                return ResourceManager.GetString("InstructionType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading instruction.
        /// </summary>
        public static string InstructionType3 {
            get {
                return ResourceManager.GetString("InstructionType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Kuvaus {
            get {
                return ResourceManager.GetString("Kuvaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Workflow.
        /// </summary>
        public static string LisaaTyolistaan {
            get {
                return ResourceManager.GetString("LisaaTyolistaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load product.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load amount.
        /// </summary>
        public static string LoadAmount {
            get {
                return ResourceManager.GetString("LoadAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading end point.
        /// </summary>
        public static string LoadingEndPoint {
            get {
                return ResourceManager.GetString("LoadingEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading point.
        /// </summary>
        public static string LoadingPoint {
            get {
                return ResourceManager.GetString("LoadingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading start point.
        /// </summary>
        public static string LoadingStartPoint {
            get {
                return ResourceManager.GetString("LoadingStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load successful.
        /// </summary>
        public static string LoadSuccessful {
            get {
                return ResourceManager.GetString("LoadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load time.
        /// </summary>
        public static string LoadTime {
            get {
                return ResourceManager.GetString("LoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to right.
        /// </summary>
        public static string Ltr {
            get {
                return ResourceManager.GetString("Ltr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Maara {
            get {
                return ResourceManager.GetString("Maara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nipema Manufactoring Management.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all the loading fields!.
        /// </summary>
        public static string MissingInformation {
            get {
                return ResourceManager.GetString("MissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Number.
        /// </summary>
        public static string Nimikekoodi {
            get {
                return ResourceManager.GetString("Nimikekoodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product number.
        /// </summary>
        public static string NoProductNumber {
            get {
                return ResourceManager.GetString("NoProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products chosen!.
        /// </summary>
        public static string NoProductsChosen {
            get {
                return ResourceManager.GetString("NoProductsChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open loading instructions.
        /// </summary>
        public static string OpenLoadingInstructions {
            get {
                return ResourceManager.GetString("OpenLoadingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open painting instructions.
        /// </summary>
        public static string OpenPaintingInstructions {
            get {
                return ResourceManager.GetString("OpenPaintingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open unloading instructions.
        /// </summary>
        public static string OpenUnloadingInstructions {
            get {
                return ResourceManager.GetString("OpenUnloadingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount ordered.
        /// </summary>
        public static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string OrderRemainingAmount {
            get {
                return ResourceManager.GetString("OrderRemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time ordered.
        /// </summary>
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing end point.
        /// </summary>
        public static string PackingEndPoint {
            get {
                return ResourceManager.GetString("PackingEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading point.
        /// </summary>
        public static string PackingPoint {
            get {
                return ResourceManager.GetString("PackingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing start point.
        /// </summary>
        public static string PackingStartPoint {
            get {
                return ResourceManager.GetString("PackingStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Paino {
            get {
                return ResourceManager.GetString("Paino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting.
        /// </summary>
        public static string Painting {
            get {
                return ResourceManager.GetString("Painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting end point.
        /// </summary>
        public static string PaintingEndPoint {
            get {
                return ResourceManager.GetString("PaintingEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting point.
        /// </summary>
        public static string PaintingPoint {
            get {
                return ResourceManager.GetString("PaintingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting start point.
        /// </summary>
        public static string PaintingStartPoint {
            get {
                return ResourceManager.GetString("PaintingStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washing pressure.
        /// </summary>
        public static string Pesupaine {
            get {
                return ResourceManager.GetString("Pesupaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washing pressure (bar).
        /// </summary>
        public static string PesupaineBar {
            get {
                return ResourceManager.GetString("PesupaineBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string ProductAdd {
            get {
                return ResourceManager.GetString("ProductAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new product.
        /// </summary>
        public static string ProductAddTitle {
            get {
                return ResourceManager.GetString("ProductAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted.
        /// </summary>
        public static string ProductDeleted {
            get {
                return ResourceManager.GetString("ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string ProductEdit {
            get {
                return ResourceManager.GetString("ProductEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string ProductEditTitle {
            get {
                return ResourceManager.GetString("ProductEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product image.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production instructions.
        /// </summary>
        public static string ProductionInstructions {
            get {
                return ResourceManager.GetString("ProductionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product number.
        /// </summary>
        public static string ProductNumber {
            get {
                return ResourceManager.GetString("ProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat treatment duration.
        /// </summary>
        public static string ProductOvenTime {
            get {
                return ResourceManager.GetString("ProductOvenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove product.
        /// </summary>
        public static string ProductRemove {
            get {
                return ResourceManager.GetString("ProductRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products and instructions.
        /// </summary>
        public static string ProductsAndInstructions {
            get {
                return ResourceManager.GetString("ProductsAndInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products awaiting treatment.
        /// </summary>
        public static string ProductsAwaitingTreatmentHeader {
            get {
                return ResourceManager.GetString("ProductsAwaitingTreatmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products deleted.
        /// </summary>
        public static string ProductsDeleted {
            get {
                return ResourceManager.GetString("ProductsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products sent to treatment.
        /// </summary>
        public static string ProductsInTreatmentHeader {
            get {
                return ResourceManager.GetString("ProductsInTreatmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products.
        /// </summary>
        public static string ProductsListAll {
            get {
                return ResourceManager.GetString("ProductsListAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string QuickLoad {
            get {
                return ResourceManager.GetString("QuickLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time view.
        /// </summary>
        public static string RealTimeView {
            get {
                return ResourceManager.GetString("RealTimeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from workflow.
        /// </summary>
        public static string RemoveFromWorkflow {
            get {
                return ResourceManager.GetString("RemoveFromWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveProduct {
            get {
                return ResourceManager.GetString("RemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove trolley.
        /// </summary>
        public static string RemoveTrolley {
            get {
                return ResourceManager.GetString("RemoveTrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading time.
        /// </summary>
        public static string RipustusAika {
            get {
                return ResourceManager.GetString("RipustusAika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to left.
        /// </summary>
        public static string Rtl {
            get {
                return ResourceManager.GetString("Rtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save instructions.
        /// </summary>
        public static string SaveInstructions {
            get {
                return ResourceManager.GetString("SaveInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful.
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save products to Excel-file.
        /// </summary>
        public static string SaveToExcel {
            get {
                return ResourceManager.GetString("SaveToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application language.
        /// </summary>
        public static string SelectLanguageOptionHeader {
            get {
                return ResourceManager.GetString("SelectLanguageOptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple products.
        /// </summary>
        public static string SelectMultiple {
            get {
                return ResourceManager.GetString("SelectMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show history from.
        /// </summary>
        public static string ShowHistoryFrom {
            get {
                return ResourceManager.GetString("ShowHistoryFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string SlowLoad {
            get {
                return ResourceManager.GetString("SlowLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading &amp; Instructions.
        /// </summary>
        public static string TabHeader1 {
            get {
                return ResourceManager.GetString("TabHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley.
        /// </summary>
        public static string Trolley {
            get {
                return ResourceManager.GetString("Trolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley details.
        /// </summary>
        public static string TrolleyDetails {
            get {
                return ResourceManager.GetString("TrolleyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley ETA.
        /// </summary>
        public static string TrolleyEstimatedArrival {
            get {
                return ResourceManager.GetString("TrolleyEstimatedArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley loaded.
        /// </summary>
        public static string TrolleyLoadedTime {
            get {
                return ResourceManager.GetString("TrolleyLoadedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley Number.
        /// </summary>
        public static string TrolleyNumber {
            get {
                return ResourceManager.GetString("TrolleyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley status.
        /// </summary>
        public static string TrolleyStatus {
            get {
                return ResourceManager.GetString("TrolleyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley to be loaded.
        /// </summary>
        public static string TrolleyToBeLoaded {
            get {
                return ResourceManager.GetString("TrolleyToBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product picture.
        /// </summary>
        public static string Tuotekuva {
            get {
                return ResourceManager.GetString("Tuotekuva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Number.
        /// </summary>
        public static string Tyokoodi {
            get {
                return ResourceManager.GetString("Tyokoodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading.
        /// </summary>
        public static string Unloading {
            get {
                return ResourceManager.GetString("Unloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Instructions.
        /// </summary>
        public static string UsageInstructions {
            get {
                return ResourceManager.GetString("UsageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use oven time.
        /// </summary>
        public static string UseOvenTime {
            get {
                return ResourceManager.GetString("UseOvenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use pressure.
        /// </summary>
        public static string UsePressure {
            get {
                return ResourceManager.GetString("UsePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in oven.
        /// </summary>
        public static string Uunitusaika {
            get {
                return ResourceManager.GetString("Uunitusaika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in oven (min).
        /// </summary>
        public static string UunitusaikaMin {
            get {
                return ResourceManager.GetString("UunitusaikaMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing time.
        /// </summary>
        public static string ValmistumisAika {
            get {
                return ResourceManager.GetString("ValmistumisAika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage location.
        /// </summary>
        public static string Varastopaikka {
            get {
                return ResourceManager.GetString("Varastopaikka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Vari {
            get {
                return ResourceManager.GetString("Vari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Väri {
            get {
                return ResourceManager.GetString("Väri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolley number.
        /// </summary>
        public static string VaunuId {
            get {
                return ResourceManager.GetString("VaunuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work assignments.
        /// </summary>
        public static string WorkAssignments {
            get {
                return ResourceManager.GetString("WorkAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to workflow.
        /// </summary>
        public static string WorkflowAddTo {
            get {
                return ResourceManager.GetString("WorkflowAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Removal Confirmation.
        /// </summary>
        public static string WorkflowRemovalConfirmation {
            get {
                return ResourceManager.GetString("WorkflowRemovalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from workflow.
        /// </summary>
        public static string WorkflowRemoveFrom {
            get {
                return ResourceManager.GetString("WorkflowRemoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
